{% set name = "langchain-anthropic" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 9ea39ed345f8b13f13bb37549130eedcec2d032eb08b4942642e758c5ba3ece5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - pydantic >=2.7.4,<3.0.0
    - langchain-core >=1.4.0,<2.0.0
    - anthropic >=0.96.0,<1.0.0

test:
  imports:
    - langchain_anthropic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AnthropicMessages and LangChain
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: This package contains the LangChain integration for Anthropic's generative models.
  doc_url: https://reference.langchain.com/python/integrations/langchain_anthropic
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/partners/anthropic

extra:
  recipe-maintainers:
    - jan-janssen
